"""
logger_factory.py

Creates a console and file logger for the mitogenome pipeline.
"""

# Imports
from __future__ import annotations
import logging
from pathlib import Path

# There are ultimately two output streams that are generated by pipeline runs:
# output created by tools, and output generated by our loggers and Snakemake. 
# Here, we define variables defining both.
TOOL_OUTPUT_EVENT = "tool_output"
PIPELINE_EVENT = "pipeline"

class ExcludeToolOutputFilter(logging.Filter):
    """
    A logging filter that prevents external-tool output from reaching the console.
    This inherits from the logging.Filter class and overrides the filter method to exclude log records with a specific name.
    """
    def filter(self, record: logging.LogRecord) -> bool:
        """
        Determines if a log record should be logged based on the 
        type of event it represents.

        Args: 
            record (logging.LogRecord): The log record to be evaluated.

        Returns:
            bool: True if the log record is not a tool output event, False otherwise.
        """
        # If no attribute is detected, PIPELINE_EVENT is assigned as the default. 
        return getattr(record, "event_type", PIPELINE_EVENT) != TOOL_OUTPUT_EVENT

def make_logger(
    *,
    name: str,
    log_file_path: str | Path,
    global_log_file_path: str | Path, 
    console_level: int = logging.INFO,
    file_level: int = logging.DEBUG
) -> logging.Logger:
    """
    This returns a logger with a concise console and detailed file output.

    A logger is keyed by both logical name and resolved logfile, which prevents two samples
    from using the same tool name from accidentally sharing the same file handler
    when they execute the same Python process.

    All logging will also output to a dedicated global logfile. Everytime this type of logger 
    is required, output will ALWAYS go to the global logger. 

    The arguments must be passed by keyword. 

    Args:
        name (str): The name of the logger.
        log_file_path (str | Path): The path to the log file to be written to (this is for a particular step of the process).
        global_log_file_path (str | Path): The path to the global log file to be written to (this is for the entire pipeline).
        console_level (int): The level of logging information to send to the console (INFO).
        file_level (int): The level of logging information to send to the log file (DEBUG).
    
    Returns:
        logging.Logger: A configured logger.
    """
    # Resolving the path to the component and global logfiles.
    component_log = Path(log_file_path).resolve()
    global_log = Path(global_log_file_path).resolve() 

    # Making parent directories for the logfiles if they do not exist.
    component_log.parent.mkdir(parents = True, exist_ok = True)
    global_log.parent.mkdir(parents = True, exist_ok = True)

    # Creating a name for the logger and creating the logger. 
    logger_name = f"mitopipeline.{name}:{component_log}"
    logger = logging.getLogger(logger_name)
    
    # Setting the level of the logger to debug - at the logger level,
    # this ensures all logged messages are passed to the handlers, 
    # where filtering occurs. 
    logger.setLevel(logging.DEBUG)

    # If there are multiple loggers that inherit from each other, this prevents from
    # double-logging.
    logger.propagate = False

    # If the logger already has handlers, we assume that the logger has been configured
    # and we return it as is. This prevents adding multiple handlers to the same logger.
    if logger.handlers:
        return logger

    # Now we format how messages look on the console.
    console_formatter = logging.Formatter("[%(levelname)s] %(message)s")

    # And now we format how messages look in the log file.
    file_formatter = logging.Formatter(
        ( 
            "%(asctime)s | %(levelname)-8s | %(name)s | "
            "%(process)d | %(threadName)s | %(message)s"
        ), datefmt = "%Y-%m-%d %H:%M:%S"
    )

    # Now we set up settings for the console level. We do a number of things here:
    # 1. We create a console handler that will output to the console.
    # 2. We set the level of the console handler to the console_level argument.
    # 3. We set the formatter of the console handler to the console_formatter we defined above.
    # 4. We add a filter to the console handler that will exclude tool output from being logged to the console. This is done by adding an instance of the ExcludeToolOutput class. 
    console_handler = logging.StreamHandler()
    console_handler.setLevel(console_level)
    console_handler.setFormatter(console_formatter)
    console_handler.addFilter(ExcludeToolOutputFilter())

    # Now we set up settings for the component/step log file. We do a number of things here:
    # 1. We create a file handler that will output to the component log file.
    # 2. We set the level of the file handler to the file_level argument.
    # 3. We set the formatter of the file handler to the file_formatter we defined above.
    component_handler = logging.FileHandler(component_log, mode = "a", encoding = "utf-8")
    component_handler.setLevel
    component_handler.setFormatter(file_formatter)

    # Now we set up settings for the global log file. We do a number of things here:
    # 1. We create a file handler that will output to the global log file.
    # 2. We set the level of the file handler to the file_level argument.
    # 3. We set the formatter of the file handler to the file_formatter we defined
    global_handler = logging.FileHandler(global_log, mode = "a", encoding = "utf-8")
    global_handler.setLevel(logging.DEBUG)
    global_handler.setFormatter(file_formatter)

    # Finally we add the handlers to the logger.
    logger.addHandler(console_handler)
    logger.addHandler(component_handler)
    logger.addHandler(global_handler)

    # Then we return the logger.
    return logger

    
