output_root: output_tmp
manifest: ctrl/config/samples.tsv

directories:
  logs: logs
  qc: qc
  trimming: trimming
  assembly: assembly
  annotation: annotation
  phylogeny: phylogeny
  reports: reports
  stats: stats
  submission: submission

tools:
  fastqc:
    threads: 4
  fastp:
    threads: 4
  getorganelle:
    threads: 8