"""fastp_stats.py

This module contains functionality for extracting data generated by fastp.
"""

# Imports
from pathlib import Path
from typing import Union
import json
import logging
from mitopipeline.models.fastp_stats import FastPStats

def parse_fastp_json(
        json_path: Path, 
        sample_id: str,
        logger: logging.Logger | None = None,
        ) -> dict[str, Union[str, float]]:
    """Parses the fastp json file and returns a dictionary of stats for the sample.
    
    Args:
        json_path (Path): The path to the fastp json file.
        sample_id (str): The sample id.
        logger (logging.Logger | None, optional): The logger to use. Defaults to None.

    Returns:
        dict[str, Union[str, float]]: A dictionary of stats for the sample.
    """
    # Checking if the json file exists.
    if not json_path.exists() or not json_path.is_file():
        if logger is not None: logger.error(f"Fastp json file not found: {json_path}")
        raise FileNotFoundError(f"Fastp json file not found: {json_path}")
    
    # Loading the json file.
    with open(json_path, "r") as f:
        data = json.load(f)
        if logger is not None: logger.info(f"Fastp json file loaded: {json_path}")
    
    # Extracting stats.
    stats = FastPStats(
        sample_id=sample_id,
        reads_in=data["summary"]["before_filtering"]["total_reads"],
        reads_out=data["summary"]["after_filtering"]["total_reads"],
        bases_in=data["summary"]["before_filtering"]["total_bases"],
        bases_out=data["summary"]["after_filtering"]["total_bases"],
        q20_rate_in=data["summary"]["before_filtering"]["q20_rate"],
        q20_rate_out=data["summary"]["after_filtering"]["q20_rate"],
        q30_rate_in=data["summary"]["before_filtering"]["q30_rate"],
        q30_rate_out=data["summary"]["after_filtering"]["q30_rate"],
        gc_content_in=data["summary"]["before_filtering"]["gc_content"],
        gc_content_out=data["summary"]["after_filtering"]["gc_content"],
        reads_removed=data["summary"]["before_filtering"]["total_reads"]
        - data["summary"]["after_filtering"]["total_reads"],
        bases_removed=data["summary"]["before_filtering"]["total_bases"]
        - data["summary"]["after_filtering"]["total_bases"],
        read_retention_rate=data["summary"]["after_filtering"]["total_reads"]
        / data["summary"]["before_filtering"]["total_reads"],
        base_retention_rate=data["summary"]["after_filtering"]["total_bases"]
        / data["summary"]["before_filtering"]["total_bases"],
        reads_passing_filtering=data["filtering_result"]["passed_filter_reads"],
        low_qual_removed=data["filtering_result"]["low_quality_reads"],
        too_many_n_removed=data["filtering_result"]["too_many_N_reads"],
        too_short_removed=data["filtering_result"]["too_short_reads"],
        too_long_removed=data["filtering_result"]["too_long_reads"],
        adapter_removed_reads=data["adapter_cutting"]["adapter_trimmed_reads"],
        adapter_removed_bases=data["adapter_cutting"]["adapter_trimmed_bases"],
    )

    # Returning stats. 
    if logger is not None: logger.info(f"Fastp stats extracted: {json_path}")
    return stats