"""
01-qc_raw.smk

Executes and validates FastQC on raw data.
"""

# Imports
from pathlib import Path

rule qc_raw:
    input: 
        """
        When the pipeline is run, a runtime manifest is generated. 
        While a passed manifest includes relative paths for both r1 and
        r2 files, the runtime manifest generates absolute paths for both r1
        and r2. 

        wc.sample is imputed by information from {sample}, and {sample}
        is ultimately derived from ctrl/Snakefile under the sample_target function.
        The sample_target() function returns a list of strings containing the required targets
        of a given step.    

        Remember: This file is a sequential extension of ctrl/Snakefile, so variables defined there
        are also in scope for this rule. 
        
        Args:
            r1: The hard-coded path for the raw r1 file, taken from the runtime manifest.
            r2: The hard-coded path for the raw r2 file, taken from the runtime manifest.
        """ 
        r1 = lambda wc: SAMPLE_TABLE.loc[wc.sample, "r1"],
        r2 = lambda wc: SAMPLE_TABLE.loc[wc.sample, "r2"]
    output:
        """
        This is where the imputation logic for this rule begins. We explicitly define each of the files
        required to be generated for this step of the pipeline. A .done file is generated by each step -
        this used as a hook for subsequent steps (subsequent steps will be looking for the .done file
        as a target).
        
        Args:
            r1_html: The absolute path for the r1 .html file generated by fastqc.
            r1_zip: The absolute path for the r1 .zip file generated by fastqc.
            r2_html: The absolute path for the r2 .html file generated by fastqc. 
            r2_zip: The absolute path for the r2 .zip file generated by fastqc. 
            done: The absolute path for the .done file generated. 
        """
        r1_html = str(JOB_DIR / "qc" / "raw" / "{sample}" / "{sample}.R1_fastqc.html"),
        r1_zip = str(JOB_DIR / "qc" / "raw" / "{sample}" / "{sample}.R1_fastqc.zip"),
        r2_html = str(JOB_DIR / "qc" / "raw" / "{sample}" / "{sample}.R2_fastqc.html"),
        r2_zip = str(JOB_DIR / "qc" / "raw" / "{sample}" / "{sample}.R2_fastqc.zip"),
        done = str(JOB_DIR / "qc" / "raw" / "{sample}" / "{sample}.qc_raw.done")
    params:
        """
        The shell runs a python script that has options - params defines
        those options.

        Args:
            output_dir: The output directory for fastqc analysis.
            working_dir: The current working directory of the mitopipeline.
            log_file: The location of the log file for this portion of the pipeline.
            threads: The number of threads to run (pulled from the config file).
        """
        output_dir = str(JOB_DIR / "qc" / "raw" / "{sample}"),
        working_dir = str(Path.cwd()),
        log_file = str(JOB_DIR / "logs" / "qc" / "raw" / "{sample}.qc_raw.log"),
        threads = config["tools"]["fastqc.raw"]["threads"]
    conda:
        "../../envs/qc.yaml"
    shell:
        """
        python -m mitopipeline.exec.run_fastqc.raw \
            --sample-id {wildcards.sample} \
            --r1 {input.r1:q} \
            --r2 {input.r2:q} \
            --output-dir {params.output_dir:q} \
            --working-dir {params.working_dir:q} \
            --log-file {params.log_file:q} \
            --threads {params.threads:q}

        test -s {output.r1_html:q}
        test -s {output.r1_zip:q}
        test -s {output.r2_html:q}
        test -s {output.r2_zip:q}
        touch {output.done:q}
        """
