"""
02-trimming.smk

Executes and validates trimming on raw data.
"""

# Imports
from pathlib import Path
from typing import Any

def fastp_optional_args(config: dict) -> str:
    """
    This function parses the config and checks for optional command-line arguments.
    It then returns a string to append to the original command.

    Args:
        config: A dictionary - this is a global variable Snakemake generates whenever --configfile is passed.
    Returns:
        str: A string containing the optional command-line arguments to be appended.
    """
    # To make things easier, we'll subset the portion of the config related to fastp. 
    fastp_config = config["tools"]["fastp"]
    
    # We'll eventually return this but joined together. 
    args = []
    
    # Dictionary mapping options that require a value - the config name is mapped to the true flag passed to fastp. 
    # For more information about these flags, see fastp documentation or see this repository's README to view
    # how to configure config.yaml.
    value_options = {
        "qualified_quality_phred": "--qualified_quality_phred",
        "length_required": "--length_required",
        "trim_front1": "--trim_front1",
        "trim_tail1": "--trim_tail1",
        "trim_front2": "--trim_front2",
        "trim_tail2": "--trim_tail2",
        "cut_window_size": "--cut_window_size",
        "cut_mean_quality": "--cut_mean_quality",
        "n_base_limit": "--n_base_limit",
        "unqualified_percent_limit": "--unqualified_percent_limit",
        "average_qual": "--average_qual"
    }

    # Now we iterate through each of the value options and
    # append values that are not None to args.
    for key, flag in value_options.items():
        value = fastp_config.get(key)
        if value is not None:
            args.append(f"{flag} {value}")
    
    # Dictionary mapping options that are boolean - the config name is mapped to the true flag passed to fastp.
    # For more informatino about these flags, see fastp documentation or see this repository's README to view
    # how to configure config.yaml.
    boolean_options = {
        "detect_adapter_for_pe": "--detect_adapter_for_pe",
        "cut_front": "--cut_front",
        "cut_tail": "--cut_tail",
        "cut_right": "--cut_right",
        "disable_quality_filtering": "--disable_quality_filtering",
        "disable_length_filtering": "--disable_length_filtering",
        "trim_poly_g": "--trim_poly_g",
        "disable_trim_poly_g": "--disable_trim_polyg",
        "trim_poly_x": "--trim_poly_x"
    }

    # Now we iterate through each of the boolean options and
    # append values that are True to args.
    for key, flag in boolean_options.items():
        if fastp_config.get(key) is True:
            args.append(flag)
    
    # Then we join args and return - this will eventually be appended to the final command sent to the terminal.
    return " ".join(args)

rule trimming:
    input:
        """
        When the pipeline is run, a runtime manifest is generated. 
        While a passed manifest includes relative paths for both r1 and
        r2 files, the runtime manifest generates absolute paths for both r1
        and r2. 

        wc.sample is imputed by information from {sample}, and {sample}
        is ultimately derived from ctrl/Snakefile under the sample_target function.
        The sample_target() function returns a list of strings containing the required targets
        of a given step.

        Remember: This file is a sequential extension of ctrl/Snakefile, so variables defined there
        are also in scope for this rule. 

        Args:
            r1: The hard-coded path for the raw r1 file, taken from the runtime manifest.
            r2: The hard-coded path for the raw r2 file, taken from the runtime manifest.
        """
        r1 = lambda wc: SAMPLE_TABLE.loc[wc.sample, "r1"],
        r2 = lambda wc: SAMPLE_TABLE.loc[wc.sample, "r2"]
    output:
        """
        This is where the imputation logic for this rule begins. We explicitly define each of the files
        required to be generated for this step of the pipeline. A .done file is generated by each step -
        this used as a hook for subsequent steps (subsequent steps will be looking for the .done file
        as a target).

        Args:
            r1: The absolute path for the trimmed r1 fastq.gz file.
            r2: The absolute path for the trimmed r2 fastq.gz file.
            html: The absolute path for the .html file generated.
            json: The absolute path for the .json file generated.
            done: The absolute path for the .done file generated. 
        """
        r1 = str(JOB_DIR / "trimming" / "{sample}" / "{sample}.R1.trimmed.fastq.gz"),
        r2 = str(JOB_DIR / "trimming" / "{sample}" / "{sample}.R2.trimmed.fastq.gz"),
        html = str(JOB_DIR / "trimming" / "{sample}" / "{sample}.fastp.html"),
        json = str(JOB_DIR / "trimming" / "{sample}" / "{sample}.fastp.json"),
        done = str(JOB_DIR / "trimming" / "{sample}" / "{sample}.trimming.done")
    params: 
        """
        The shell runs a python script that has options - params defines
        those options.
        """
        output_dir = str(JOB_DIR / "trimming" / "{sample}"),
        working_dir = str(Path.cwd()),
        log_file = str(JOB_DIR / "logs" / "trimming" / "{sample}.trimming.log"),
        threads = config["tools"]["trimming"]["threads"],
        optional_args = fastp_optional_args(config)
    conda:
        "../../envs/trimming.yaml"
    shell:
        """
        python -m mitopipeline.exec.run_fastp \
            --sample-id {wildcards.sample} \
            --in1 {input.r1:q} \
            --in2 {input.r2:q} \
            --output_dir {params.output_dir:q} \
            --working_dir {params.working_dir:q} \
            --threads {params.threads:q}
        
        test -s {output.r1:q}
        test -s {output.r2:q}
        test -s {output.html:q}
        test -s {output.json:q}
        touch {output.done:q}
        """


