"""
05a-blast_config.smk

Rules for setting up a local BLAST database
if not performing remote BLAST searches.
"""

# Imports
from pathlib import Path
import shlex

def blast_setup_optional_args() -> str:
    """
    This function parses the config and checks for optional command-line arguments.
    It then returns a string to append to the original command.

    Args:
        config: A dictionary - this is a global variable Snakemake generates whenever --configfile is passed.
    Returns:
        str: A string containing the optional command-line arguments to be appended.
    """
    # To make things easier, we'll subset the portion of the config related to blast database setup.
    blast_config = config["tools"]["blast"]

    # We start with an empty list. This will be eventually joined together and appended
    # to the rest of a command.
    args = []

    # Dictionary mapping options that require a value - the config name is mapped to the true flag passed to blast setup. 
    # For more information about these flags, see makeblastdb documentation or see this repository's README to view
    # how to configure config.yaml. 
    value_options = {
        "entrez_email": "--entrez-email",
        "entrez_api_key": "--entrez-api-key",
        "ncbi_query": "--ncbi-query"
    }
    
    # Now we iterate through each of the value options and
    # append values that are not None to args.
    for key, flag in value_options.items():
        value = tool_config.get(key)
        if value is not None:
            args.append(f"{flag} {value}")
    
    # Dictionary mapping options that are boolean - the config name is mapped to the true flag passed to blast setup.
    # For more information about these flags, see makeblastdb documentation or see this repository's README to view
    # how to configure config.yaml.
    boolean_options = {
        "parse_seqids": "--parse-seqids",
        "overwrite_database": "--overwrite",
    }

    # Now we iterate through each of the boolean options and
    # append values that are True to args.
    for key, flag in boolean_options.items():
        if tool_config.get(key) is True:
            args.append(flag)

    # Then we join args and return - this will eventually be appended to the final command sent to the terminal.
    return " ".join(args)

def blast_reference_input() -> str:
    """
    This function obtains the location of a FASTA dependency only if 
    a custom FASTA is utilized for the database.

    Returns:
        str: A string with the location of the custom FASTA. Empty string if none is provided
        in the config. 
    """
     # To make things easier, we'll subset the portion of the config related to blast database setup.
    blast_config = config["tools"]["blast"]

    # Returns if mode local and a fasta file is provided. 
    if blast_config.get("mode") == "local" and blast_config.get("database_source") == "fasta":
        return str(Path(blast_config.get("reference_fasta")).resolve())

    # If NCBI mode is used (under blast/mode in the config), this file is generated by the pipeline automatically. 
    return ""

rule blast_database_setup.smk:
    """
    This either builds or downloads the selected blast database.
    """
    input:
        """
        The only input is the file required to be generated for the blast database.
        This is inferred by the above function, blast_reference_input(). 
        """
        reference = blast_reference_input()
    output:
        """
        The only output is a done file, marking that the database has been created.

        Args:
            done: The done file generated once the blast database has been created.
        """
        done = str(JOB_DIR / "setup" / "blast" / "blast_database.done")
    params: 
        database_source = 